{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: obtrace-system
  labels:
    app.kubernetes.io/name: obtrace-zero
    app.kubernetes.io/component: operator
{{- end }}
